
[[plugins]]
repo = 'Shougo/vimproc' 
[[plugins]]
repo = 'Shougo/unite.vim' 
[[plugins]]
repo = 'Shougo/neocomplete.vim' 
[[plugins]]
repo = 'Shougo/neosnippet.vim' 
[[plugins]]
repo = 'Shougo/neosnippet-snippets' 
[[plugins]]
repo = 'Shougo/vimfiler.vim' 
[[plugins]]
repo = 'scrooloose/syntastic' 
[[plugins]]
repo = 'thinca/vim-quickrun' 
[[plugins]]
repo = 'scrooloose/nerdcommenter' 
[[plugins]]
repo = 'davidhalter/jedi-vim' 
[[plugins]]
repo = 'thinca/vim-ref' 
[[plugins]]
repo = 'taka84u9/vim-ref-ri' 
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'alpaca-tc/alpaca_powertabline'
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'vim-scripts/Align'
[[plugins]]
repo = 'sjl/gundo.vim'
[[plugins]]
repo = 'lambdalisue/vim-django-support'
[[plugins]]
repo = 'fatih/vim-go'
[[plugins]]
repo = 'stephpy/vim-yaml'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugin]]
repo = 'tomasr/molokai'
